In [1]:
import pandas as pd
import joblib

from sklearn.cluster import KMeans

In [2]:
#load the dataset
df = pd.read_csv("../../processed_scaled.csv")

print(df.shape)
df.head()

(7043, 15)

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,Contract,MonthlyCharges,Churn,internet_fiber,TotalCharges,TenureGroup_13-24m,TenureGroup_25-48m,TenureGroup_49-72m,HighValueCustomer
0,0,0,0,-1.277445,0,0,0,-1.321350,1,False,-0.995538,False,False,False,0
1,1,0,0,0.351370,1,0,1,-1.321350,0,False,-0.553953,False,True,False,0
2,0,0,1,0.799294,1,0,0,-1.520755,0,False,-0.570291,False,False,True,0
3,0,0,0,-1.277445,1,0,1,0.373593,1,False,-0.973018,False,False,False,0
4,1,0,0,1.410099,1,0,0,-0.457261,0,True,0.502321,False,False,True,0

In [3]:
print(df.shape)
print(df.head())

(7043, 15)
   gender  SeniorCitizen  Dependents    tenure  PhoneService  MultipleLines  \
0       0              0           0 -1.277445             0              0
1       1              0           0  0.351370             1              0
2       0              0           1  0.799294             1              0
3       0              0           0 -1.277445             1              0
4       1              0           0  1.410099             1              0

   Contract  MonthlyCharges  Churn  internet_fiber  TotalCharges  \
0         0       -1.321350      1           False     -0.995538
1         1       -1.321350      0           False     -0.553953
2         0       -1.520755      0           False     -0.570291
3         1        0.373593      1           False     -0.973018
4         0       -0.457261      0            True      0.502321

   TenureGroup_13-24m  TenureGroup_25-48m  TenureGroup_49-72m  \
0               False               False               False
1               False                True               False
2               False               False                True
3               False               False               False
4               False               False                True

   HighValueCustomer
0                  0
1                  0
2                  0
3                  0
4                  0

In [4]:
# Remove duplicate rows
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)
print("Duplicate Rows after removal:", df.duplicated().sum())

Shape after removing duplicates: (6741, 15)
Duplicate Rows after removal: 0

In [5]:
X = df.drop("Churn", axis=1)

print(X.shape)

(6741, 14)

In [6]:
#Train the K-Means Model
kmeans = KMeans(
    n_clusters=4,
    init="k-means++",
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(X)

In [7]:
#Check cluster sizes
print(df["Cluster"].value_counts().sort_index())

Cluster
0    1318
1    1708
2    2215
3    1500
Name: count, dtype: int64

In [8]:



print("Model saved successfully.")

Model saved successfully.

In [9]:
#Display Cluster Centers
centers = pd.DataFrame(
    kmeans.cluster_centers_,
    columns=X.columns
)

centers

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,Contract,MonthlyCharges,internet_fiber,TotalCharges,TenureGroup_13-24m,TenureGroup_25-48m,TenureGroup_49-72m,HighValueCustomer
0,0.509105,0.078907,0.441578,0.736421,0.745827,0.401366,0.699545,-0.985150,0.452200,-0.227644,1.387779e-16,0.457511,5.424886e-01,-2.220446e-16
1,0.499415,0.264052,0.210187,-0.336227,1.000000,0.413934,0.680913,0.808128,0.424473,-0.063490,2.318501e-01,0.514637,8.881784e-16,7.968384e-01
2,0.502032,0.118736,0.263205,-0.959532,0.858691,0.424831,0.715576,-0.576874,0.439729,-0.830367,2.695260e-01,0.024831,9.992007e-16,1.998401e-15
3,0.504667,0.208000,0.351333,1.257724,0.983333,0.446000,0.711333,0.959290,0.446667,1.608111,1.387779e-16,0.022000,9.780000e-01,7.866667e-01

In [10]:


# Save the trained model
joblib.dump(kmeans, "kmeans_model.pkl")

print("K-Means Model saved successfully.")

K-Means Model saved successfully.

In [11]:
df.to_csv("clustered_customer_data.csv", index=False)

print("Clustered dataset saved successfully!")

Clustered dataset saved successfully!

In [12]:
loaded_model = joblib.load("kmeans_model.pkl")

print(loaded_model)

KMeans(n_clusters=4, n_init=10, random_state=42)